import numpy as np
import cv2
from collections import deque

def get_avg(pos_list):
    ax = sum([i[0] for i in pos_list]) / len(pos_list)
    ay = sum([i[1] for i in pos_list]) / len(pos_list)
    az = sum([i[2] for i in pos_list]) / len(pos_list)
    return (ax, ay, az,)

class HandSmoother:
    def __init__(self, window=5):
        self.window = deque(maxlen=window)
    def update(self, x, y, z):
        self.window.append((x, y, z))
        return get_avg(list(self.window))
    

class Calibration():
    def __init__(self):
        calibrated = False
        min_x = None
        min_y = None
        min_z = None
        max_x = None
        max_y = None
        max_z = None

    def update_min(self, x, y, z):
        self.min_x = x
        self.min_y = y
        self.min_z = z
    def update_max(self, x, y, z): 
        self.max_x = x
        self.max_y = y
        self.max_z = z
    # checks calibration, bounds and normalization
    def normalize_and_check(self, x, y, z, margin=0.05):
        if not self.calibrated or self.max_x == self.min_x or self.max_y == self.min_y or self.max_z == self.min_z:
            return (0, 0, 0,), False
        x_norm = (x - self.min_x) / (self.max_x - self.min_x)
        y_norm = (y - self.min_y) / (self.max_y - self.min_y)
        z_norm = (z - self.min_z) / (self.max_z - self.min_z)
        in_bounds = (-margin <= x_norm <= 1.0 + margin and
                     -margin <= y_norm <= 1.0 + margin and
                     -margin <= z_norm <= 1.0 + margin)
        return (x_norm, y_norm, z_norm,), in_bounds


# GENERATED BY CHAT BUT NOT USED (yet)
class Calibration4():
    def __init__(self):
        # Z bounds (same as your original)
        self.min_x = 0
        self.min_y = 0
        self.min_z = 0
        self.max_x = 0
        self.max_y = 0
        self.max_z = 0

        # 4-point XY calibration
        self.top_left = None
        self.top_right = None
        self.bottom_left = None
        self.bottom_right = None

        self.xy_transform = None

    def update_min(self, x, y, z):
        self.min_x = x
        self.min_y = y
        self.min_z = z

    def update_max(self, x, y, z):
        self.max_x = x
        self.max_y = y
        self.max_z = z

    def set_xy_points(self, top_left, top_right, bottom_left, bottom_right):
        """
        Store the 4 calibration corners and compute perspective transform.
        """

        self.top_left = top_left
        self.top_right = top_right
        self.bottom_left = bottom_left
        self.bottom_right = bottom_right

        src = np.array([
            top_left,
            top_right,
            bottom_left,
            bottom_right
        ], dtype=np.float32)

        dst = np.array([
            [0, 0],
            [1, 0],
            [0, 1],
            [1, 1]
        ], dtype=np.float32)

        self.xy_transform = cv2.getPerspectiveTransform(src, dst)

    def normalize(self, x, y, z):
        # ---- XY normalization via perspective transform ----
        if self.xy_transform is not None:

            pt = np.array([[[x, y]]], dtype=np.float32)

            transformed = cv2.perspectiveTransform(pt, self.xy_transform)

            x_norm = transformed[0][0][0]
            y_norm = transformed[0][0][1]

        else:
            # fallback to min/max scaling
            x_norm = (x - self.min_x) / (self.max_x - self.min_x)
            y_norm = (y - self.min_y) / (self.max_y - self.min_y)

        # ---- Z normalization (min/max) ----
        z_norm = (z - self.min_z) / (self.max_z - self.min_z)

        # clamp everything to [0,1]
        x_norm = max(0.0, min(1.0, x_norm))
        y_norm = max(0.0, min(1.0, y_norm))
        z_norm = max(0.0, min(1.0, z_norm))

        return x_norm, y_norm, z_norm