import math

# generated by CLAUDE
class HandSmoother:
    """
    Adaptive exponential smoother with outlier rejection.
    Three layers of protection:
      1. Outlier rejection  - spikes from bad MediaPipe frames are dropped
      2. Adaptive smoothing - fast movement gets less smoothing (less lag),
                              slow/still movement gets more smoothing (less jitter)
      3. Exponential weight - recent frames always matter more than old ones
    """
    def __init__(
        self,
        base_alpha: float = 0.4,    # smoothing at rest: 0=frozen, 1=no smoothing
        fast_alpha: float = 0.9,    # smoothing during fast movement
        speed_scale: float = 0.08,  # how much movement triggers "fast" mode
        outlier_thresh: float = 0.15, # max plausible single-frame delta
        warmup_frames: int = 5,     # frames before outlier rejection activates
    ):
        self.base_alpha = base_alpha
        self.fast_alpha = fast_alpha
        self.speed_scale = speed_scale
        self.outlier_thresh = outlier_thresh
        self.warmup_frames = warmup_frames

        self.smoothed = None        # current smoothed position (x, y, z)
        self.frame_count = 0

    def _distance(self, a, b):
        return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))

    def _alpha(self, speed: float) -> float:
        """
        Interpolate alpha between base and fast based on movement speed.
        Faster hand = higher alpha = less smoothing = less lag.
        """
        t = min(speed / self.speed_scale, 1.0)
        return self.base_alpha + t * (self.fast_alpha - self.base_alpha)

    def update(self, x: float, y: float, z: float):
        new_pos = (x, y, z)
        self.frame_count += 1

        # --- WARMUP: not enough history yet, accept everything ---
        if self.smoothed is None or self.frame_count <= self.warmup_frames:
            if self.smoothed is None:
                self.smoothed = new_pos
            else:
                # simple average during warmup to seed a stable starting value
                a = 1.0 / self.frame_count
                self.smoothed = tuple(
                    a * n + (1 - a) * s
                    for n, s in zip(new_pos, self.smoothed)
                )
            return self.smoothed

        # --- OUTLIER REJECTION ---
        delta = self._distance(new_pos, self.smoothed)
        if delta > self.outlier_thresh:
            # frame is suspiciously far from current position — drop it silently
            return self.smoothed

        # --- ADAPTIVE EXPONENTIAL SMOOTHING ---
        alpha = self._alpha(delta)
        self.smoothed = tuple(
            alpha * n + (1 - alpha) * s
            for n, s in zip(new_pos, self.smoothed)
        )
        return self.smoothed

    def reset(self):
        self.smoothed = None
        self.frame_count = 0